---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Сайт должен быть доступен на различных устройствах
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы 
- Важно, чтобы сайт мог обрабатывать большое количество трафика 
implicit:
- конкретное требование по необходимой нагрузке, какую сайт должен выдерживать
- после нажатия на кнопку "в корзину" должно появляться окно с подтверждением и уведомлением о том, что товар добавлен в корзину 
- наличие личного кабинета,где можно было бы отслеживать сделанные заказы 
- в корзине должна отображаться общая стоимость товаров в корзине на этапе когда заказ еще не оформлен 
- в корзине должна быть возможность изменить количество каждой единицы товара как в меньшую, так и в большую сторону
- при нажатии на удаление товара из корзины, товар должен удаляться полностью, а не по убыванию единиц товара 
- после того, как заказ оформлен, корзина должна обнулиться 




