---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Сайт должен быть доступен на различных устройствах
implicit:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы #нужно больше конкретики, что в понимании заказчика удобно и какая скорость работы требуется 
- Важно, чтобы сайт мог обрабатывать большое количество трафика #большое - это какое? необходимо конкретизировать сколько человек может одновременно юзать сайт и делать заказы, чтобы сайт не упал



